select 0,
OriginalFoodCode,
OriginalFoodName,
EnglishFoodName,
ScientificFoodName,
OtherFoodNames,
OriginalFoodGroupCode,
FoodGroupIS1,
FoodGroupIS2,
FoodGroupIS3,
CodexFoodStandards,
ArticleNumber,
E_number,
INS_code,
0,
CODEXAdditives,
CODEXFood,
CODEXContaminants,
FAOBalanceSheet,
CIAAFood,
EuroCode2,
AgriculturalConditions,
Cuisine,
EdiblePortion,
WastePortion,
NatureofEdiblePortion,
NatureofWaste,
TypicalServingSize,
TypicalWeightperPiece,
Colour,
FinalPreparation,
SpecificGravity,
NitrogenProteinFactor,
FattyAcidFactor,
GenericImage,
SpecificImage,
Producer,
Distributor,
Retailer,
AreaOfOrigin,
AreaOfProcessing,
AreaofConsumption,
WebPublishReady,
ListOfIngredients,
0,
0,
GeneratedBy,
0,
UpdatedBy from food where WebPublishReady = 'J'

select
0,
cv.OriginalFoodCode,
OriginalComponentCode,
0,
0,
SelectedValue,
Unit,
Matrixunit,
ValueType,
AcquisitionType,
0,
DateofEvaluation,
DateofEvaluationDisp,
N,
AnalyticalPortionSize,
NoofAnalyticalPortionReplicates,
Mean,
Median,
[Minimum],
Maximum,
StandardDeviation,
StandardError,
0,
0,
0,
0,
NoofPrimarySampleUnits,
0,
OriginalReferenceCode,
QI_Eurofir,
QualityAssessmentFK,
SamplingStrategy,
0,
0,
0,
0,
cv.GeneratedBy,
0,
cv.UpdatedBy
from ComponentValue cv, Food f where f.WebPublishReady = 'J' and f.OriginalFoodCode = cv.OriginalFoodCode
and cv.OriginalComponentCode in (1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 23, 24, 28, 29, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 44, 137, 138);

select * from food

select c.* from sys.columns c, sys.tables t where t.name = 'Food' and c.object_id = t.object_id
select c.* from sys.columns c, sys.tables t where t.name = 'ComponentValue' and c.object_id = t.object_id
